public class mygameengine {
    fun output_console(String output_console_text) { println(output_console_text) }
    fun input_console(String input_console_text) { println(input_console_text) String c = readLine() }
    fun choicecountry(String name_country)    
    fun shutdown(Int status) { exit(status) }
    fun return_on(Boolean return_on_status) { return_on_status }
    fun info() { println("My Github : https://github.com/BucTer123/") println("My Forgejo : https://v15.next.forgejo.org/BucTer123/") }
    fun output_list_countries(String list_countries) {
        if (list_countries == "TRUE") {
            println("Afganistan\n")
            println("Albania\n")
            println("Algeria\n")
            println("Andorra\n")
            println("Antigua and Barbuda\n")
            println("Argentina\n")
            println("Armenia\n")
            println("Australia\n")
            println("Austria\n")
            println("Azerbaijan\n")
            println("Bahamas\n")
            println("Bahrain\n")
            println("Bangladesh\n")
            println("Barbados\n")
            println("Belarus\n")
            println("Belgium\n")
            println("Belize\n")
            println("Benin\n")
            println("Bhutan\n")
            println("Bolivia\n")
            println("Bosnia and Herzegovina\n")
            println("Botswana\n")
            println("Brazil\n")
            println("Brunei\n")
            println("Bulgaria\n")
            println("Burkina Faso\n")
            println("Burundi\n")
            println("Cabo Verde\n")
            println("Cambodia\n")
            println("Cameroon\n")
            println("Canada\n")
            println("Central African Republic\n")
            println("Chad\n")
            println("Chile\n")
            println("China\n")
            println("Colombia\n")
            println("Comoros\n")
            println("Congo (Republic of the Congo)\n")
            println("Costa Rica\n")
            println("Côte d’Ivoire\n")
            println("Croatia\n")
            println("Cuba\n")
            println("Cyprus\n")
            println("Czech Republic\n")
            println("Democratic Republic of the Congo \n")
            println("Denmark\n")
            println("Djibouti\n")
            println("Dominica\n")
            println("Dominican Republic\n")
            println("Ecuador\n")
            println("Egypt\n")
            println("El Salvador\n")
            println("Equatorial Guinea\n")
            println("Eritrea\n")
            println("Estonia\n")
            println("Eswatini\n")
            println("Ethiopia\n")
            println("Fiji\n")
            println("Finland\n")
            println("France\n")
            println("Gabon\n")
            println("Gambia\n")
            println("Georgia\n")
            println("Germany\n")
            println("Ghana\n")
            println("Greece\n")
            println("Grenada\n")
            println("Guatemala\n")
            println("Guinea\n")
            println("Guinea-Bissau\n")
            println("Guyana\n")
            println("Haiti\n")
            println("Honduras\n")
            println("Hungary\n")
            println("Iceland\n")
            println("India\n")
            println("Indonesia\n")
            println("Iran\n")
            println("Iraq\n")
            println("Ireland\n")
            println("Israel\n")
            println("Italy\n")
            println("Jamaica\n")
            println("Japan\n")
            println("Jordan\n")
            println("Kazakhstan\n")
            println("Kenya\n")
            println("Kiribati\n")
            println("Kuwait\n")
            println("Kyrgyzstan\n")
            println("Laos\n")
            println("Latvia\n")
            println("Lebanon\n")
            println("Lesotho\n")
            println("Liberia\n")
            println("Libya\n")
            println("Liechtenstein\n")
            println("Lithuania\n")
            println("Luxembourg\n")
            println("Madagascar\n")
            println("Malawi\n")
            println("Malaysia\n")
            println("Maldives\n")
            println("Mali\n")
            println("Malta\n")
            println("Marshall Islands\n")
            println("Mauritania\n")
            println("Mauritius\n")
            println("Mexico\n")
            println("Micronesia\n")
            println("Moldova\n")
            println("Monaco\n")
            println("Mongolia\n")
            println("Montenegro\n")
            println("Morocco\n")
            println("Mozambique\n")
            println("Myanmar\n")
            println("Namibia\n")
            println("Nauru\n")
            println("Nepal\n")
            println("Netherlands\n")
            println("New Zealand\n")
            println("Nicaragua\n")
            println("Niger\n")
            println("Nigeria\n")
            println("North Korea\n")
            println("North Macedonia\n")
            println("Norway\n")
            println("Oman\n")
            println("Pakistan\n")
            println("Palau\n")
            println("Panama\n")
            println("Papua New Guinea\n")
            println("Paraguay\n")
            println("Peru\n")
            println("Philippines\n")
            println("Poland\n")
            println("Portugal\n")
            println("Qatar\n")
            println("Romania\n")
            println("Russia\n")
            println("Rwanda\n")
            println("Saint Kitts and Nevis\n")
            println("Saint Lucia\n")
            println("Saint Vincent and the Grenadines\n")
            println("Samoa\n")
            println("San Marino\n")
            println("Sao Tome and Principe\n")
            println("Saudi Arabia\n")
            println("Senegal\n")
            println("Serbia\n")
            println("Seychelles\n")
            println("Sierra Leone\n")
            println("Singapore\n")
            println("Slovakia\n")
            println("Slovenia\n")
            println("Solomon Islands\n")
            println("Somalia\n")
            println("South Africa\n")
            println("South Korea\n")
            println("South Sudan\n")
            println("Spain\n")
            println("Sri Lanka\n")
            println("Sudan\n")
            println("Suriname\n")
            println("Sweden\n")
            println("Switzerland\n")
            println("Syria\n")
Taiwan
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Tonga
Zimbabwe
        }
    }
}
